//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BUMPED_BACK_CENTER1 = "bumped_back_center1";
        
        public const string BUMPED_BACK_LEFT1 = "bumped_back_left1";
        
        public const string BUMPED_BACK_RIGHT1 = "bumped_back_right1";
        
        public const string BUMPED_FRONT_CENTER1 = "bumped_front_center1";
        
        public const string BUMPED_FRONT_RIGHT1 = "bumped_front_right1";
        
        public const string BUMPED_FRONT_LEFT1 = "bumped_front_left1";
    }
}
